services:
  cctv_app:
    build:
      context: .
      dockerfile: docker/frankenphp/Dockerfile
    image: cctv/dashboard:dev
    network_mode: host
    container_name: cctv_app_dev
    env_file:
      - .env
    restart: unless-stopped
