services:
  cctv_app:
    build:
      context: .
      dockerfile: docker/frankenphp/Dockerfile
    image: cctv/dashboard:local
    container_name: cctv_app_local
    network_mode: host
    env_file:
      - .env
    restart: unless-stopped
