services:
  cctv_app:
    build:
      context: .
      dockerfile: docker/frankenphp/Dockerfile
    image: cctv/dashboard:latest
    container_name: cctv_app_production
    network_mode: host
    env_file:
      - .env
    restart: always
